language: python
python: 
- "2.7"
env: 
  global: 
    secure: CR0RYDzX5o+Jwd7wAE4XES8Gwpk6X9JbRREb7dFhfUgXoW1gLOlRlz5lI9CtXw4ib/XtYvm3gcpJADn63S+X2edVt5loQcB7wH8LhPYfdkhmDm+DUpugq4TZnWjkeYKkOQpu7l65dKCfO9nnXiuzZlJ4jIW7vhh3IPmHLUWUzAw=
before_install:
 - yes | sudo add-apt-repository ppa:irie/blender
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-sphinx
 - sudo apt-get install -qq blender
 - sudo apt-get install -qq pylint
 - sudo apt-get install -qq python-all-dev
 - sudo apt-get install -qq python-dev cython libavcodec-dev libavformat-dev libswscale-dev
 - sudo apt-get install -qq ffmpeg sox libsox-fmt-mp3
 - sudo apt-get install -qq libimage-exiftool-perl
 - sudo apt-get build-dep python-matplotlib
install: 
- pip install matplotlib
- git clone https://github.com/ayush1794/damn-test-files
- git clone https://github.com/wgwang/thrift.git
- cd thrift/lib/py3/
- sudo python3 setup.py install
- cd ../../..
- pip install coveralls
script: 
- python setup.py test
- sudo python setup.py develop
- coverage run --source=damn_at setup.py test
after_script:
- ./bin/update-gh-pages.sh
after_success:
  coveralls
